server:
  port: 9009
spring:
  application:
    name: spirng-debase
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: cs123456
  redis:
    # redis数据库索引(默认为0)
    database: 0
    # redis服务器地址（默认为localhost）
    host: localhost
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password: 123456
    # redis连接超时时间（单位毫秒）
    timeout: 1000

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.demo.pojo
  global-config:
    db-config:
      id-type: auto

#  configuration:
    # 配置日志，显示数据库操作语句
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl